spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_db?serverTimezone=Asia/Seoul
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:./uploads/
      cache:
        period: 3600
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}

