spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_db?serverTimezone=Asia/Seoul
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

